name: VerifyIssue

on:
  pull_request:
    types: [edited, synchronize, opened, reopened]
  check_run:


jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Verify Linked Issue
        uses: hattan/verify-linked-issue-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: '.github/VERIFY_PR_COMMENT_TEMPLATE.md'