on: 
  pull_request:
    types: [edited, synchronize, opened, reopened]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Verify Linked Issue
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify Linked Issue
        uses: hattan/verify-linked-issue-action@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}