name: VerifyIssue

on:
  pull_request:
    types: [edited, synchronize, opened, reopened]
  check_run:



jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify Linked Issue
        uses: ./ 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Hello hello_world_job
        run: echo "Hello World"

    