# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

name: Labeler
on: [pull_request]

jobs:
  verify-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            let isLinked=false;
            let body = context.payload.pull_request.body;
            const re = /#(.*?)[\s]/g;
            const matches = body.match(re);
            if(matches){
              matches.forEach(match => {
               var issueId = match.replace('#','').trim();
               console.log("found hash in body!")
               isLinked = true;
              });
            }
            if(!isLinked){
              let pull = await github.issues.listEvents({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number 
              });

              if(pull.data){
                console.log(pull.data);
                pull.data.forEach(item => {
                  console.log(item);
                  if (item.event == "connected"){
                    isLinked = true;
                  }
                });
              }
            }
            if(isLinked){
              console.log("is linked!");
            }
            else{
              console.log("nope");
            }


